# Generated by Django 5.2.3 on 2025-06-23 14:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('heading', 'Heading'), ('code', 'Code'), ('latex', 'LaTeX'), ('image', 'Image'), ('table', 'Table'), ('list', 'List')], default='text', max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='notes.note')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='blocks.block')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['note', 'order'], name='blocks_bloc_note_id_7332bb_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['note', 'is_deleted'], name='blocks_bloc_note_id_d88fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['block_type'], name='blocks_bloc_block_t_f9f004_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('note', 'order')},
        ),
        migrations.AddIndex(
            model_name='blockversion',
            index=models.Index(fields=['block', '-created_at'], name='blocks_bloc_block_i_997415_idx'),
        ),
        migrations.AddIndex(
            model_name='blockversion',
            index=models.Index(fields=['created_by'], name='blocks_bloc_created_3019c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockversion',
            unique_together={('block', 'version_number')},
        ),
    ]
