# Generated by Django 5.2.3 on 2025-06-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='block',
            name='blocks_bloc_note_id_d88fcf_idx',
        ),
        migrations.RemoveField(
            model_name='block',
            name='is_deleted',
        ),
    ]
