# Generated by Django 5.2.3 on 2025-06-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='note',
            name='notes_note_is_dele_a58d5a_idx',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_deleted',
        ),
    ]
